apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /*
        backend:
          serviceName: adlfrontend-service
          servicePort: 80
      - path: /adl-api/v1/*
        backend:
          serviceName: adlbackend-service
          servicePort: 8081
      - path: /account/*
        backend:
          serviceName: account-service
          servicePort: 8083

          
