apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: adlrecorder
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adlrecorder
            image: f73-g1.cloudogu.net/nexus/hektor/adlrecorder:1.0
            ports:
            - name: http
              containerPort: 8080
            env:
            - name: ADL_BACKEND_IP
              value: adlbackend-service
          imagePullSecrets:
          - name: dockreg
          restartPolicy: Never
