apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: adlrecorder
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adlrecorder
<<<<<<< HEAD
            image: f73-g1.cloudogu.net/nexus/hektor/adlrecorder:1.4
=======
            image: f73-g1.cloudogu.net/nexus/hektor/adlrecorder:1.0
>>>>>>> b319b814b2c18d77e5a26ff19459498efbacaf20
            ports:
            - name: http
              containerPort: 8080
            env:
            - name: ADL_BACKEND_IP
              value: adlbackend-service
          imagePullSecrets:
          - name: dockreg
          restartPolicy: Never
