apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: adlrecorder
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: adlrecorder
            image: f73-g1.cloudogu.net/nexus/hektor/adlrecorder:2.31
            ports:
            - name: http
              containerPort: 8080
            env:
            - name: ADL_BACKEND_IP
              value: adlbackendservice
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: adminsecret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adminsecret
                  key: PASSWORD
          imagePullSecrets:
          - name: dockreg
          - name: adminsecret
          restartPolicy: Never
