apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: f73-g1.cloudogu.net/nexus/hektor/account:latest
          ports:
            - name: http
              containerPort: 8083
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: adlis-postgresql-secret
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adlis-postgresql-secret
                  key: password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: adlis-postgresql-secret
                  key: database
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: adlis-postgresql-secret
                  key: host
      imagePullSecrets:
        - name: adlis-postgresl-secret
        - name: dockreg
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
  namespace: default
  labels:
    app: account
spec:
  selector:
    app: account
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 8083
      targetPort: 8083