apiVersion: apps/v1
kind: Deployment
metadata:
  name: adlfrontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adlfrontend
  template:
    metadata:
      labels:
        app: adlfrontend
    spec:
      containers:
        - name: adlfrontend
          image: f73-g1.cloudogu.net/nexus/hektor/adlfrontend:1.12
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: dockreg
---
apiVersion: v1
kind: Service
metadata:
  name: adlfrontend-service
  namespace: default
  labels:
    app: adlfrontend
spec:
  selector:
    app: adlfrontend
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
