apiVersion: apps/v1
kind: Deployment
metadata:
  name: adlbackend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adlbackend
  template:
    metadata:
      labels:
        app: adlbackend
    spec:
      containers:
        - name: adlbackend
          image: f73-g1.cloudogu.net/nexus/hektor/adlbackend:2.21
          ports:
            - name: http
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongosecret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongosecret
                  key: MONGO_PASSWORD
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongosecret
                  key: MONGO_DATABASE
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: mongosecret
                  key: MONGO_HOST
      imagePullSecrets:
        - name: mongosecret
        - name: dockreg
---
apiVersion: v1
kind: Service
metadata:
  name: adlbackend-service
  namespace: default
  labels:
    app: adlbackend
spec:
  selector:
    app: adlbackend
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081